# Generated by Django 4.2 on 2024-04-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Product',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
