# Generated by Django 4.2 on 2024-04-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_comment_product_product_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
